[package]
name = "example3"
version = "0.0.0"
edition = "2024"
authors = ["Matthew Scroggs <rust@mscroggs.co.uk>",]
description = "crate for testing cargo-templated-examples"
license = "MIT"
repository = "https://github.com/mscroggs/cargo-templated-examples"
readme = "../README.md"

[[example]]
name = "this_example"
path = "examples/subexamples/this_example.rs"
