name: ✨

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  style-checks:
    name: Style checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt,clippy
      - uses: actions/checkout@v4

      - name: Rust style checks
        run: |
          cargo fmt -- --check
          cargo clippy --features "strict" -- -D warnings
